#!/bin/bash
echo "enter the marks"
read marks
if [ $marks -ge 35 ]
then 
    echo "you passed"
if [ $marks -ge 95]
then
    echo "you got destination"
fi

if  [ $marks -ge 75]
then 
      echo "you got firstclass"
fi
 
if [ $marks -ge 55]
then 
     echo "you got secondclass"
fi

else 
     echo "fail"
fi
